[postgres]
username = ""
host = ""
port = ""
dbanme = ""
password = ""
sslmode = "disable"

[sqlite]
dbpath = "./database/db1.sqlite3"

[telegram]
token = ""
host = "api.telegram.org"

[server]
url = ""
port = "443"

[tls]
certificatePath = ""
privateKeyPath = ""
